[proxy]
proxy01 ansible_host=10.10.0.11
proxy02 ansible_host=10.10.0.12

[zookeeper]
zk01 ansible_host=10.10.0.21 myid=1
zk02 ansible_host=10.10.0.22 myid=2
zk03 ansible_host=10.10.0.23 myid=3

[clickhouse_s1]
ch-s1-r1 ansible_host=10.10.0.31 shard=1 replica=1
ch-s1-r2 ansible_host=10.10.0.32 shard=1 replica=2
ch-s1-r3 ansible_host=10.10.0.33 shard=1 replica=3

[clickhouse_s2]
ch-s2-r1 ansible_host=10.10.0.41 shard=2 replica=1
ch-s2-r2 ansible_host=10.10.0.42 shard=2 replica=2
ch-s2-r3 ansible_host=10.10.0.43 shard=2 replica=3

[clickhouse_s3]
ch-s3-r1 ansible_host=10.10.0.51 shard=3 replica=1
ch-s3-r2 ansible_host=10.10.0.52 shard=3 replica=2
ch-s3-r3 ansible_host=10.10.0.53 shard=3 replica=3

[clickhouse:children]
clickhouse_s1
clickhouse_s2
clickhouse_s3

[all:vars]
ansible_user=admin
